# Generated by Django 4.2 on 2024-01-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Koots', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
