# Generated by Django 4.2 on 2024-01-26 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Koots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.CharField(choices=[('NP', 'Новая Почта'), ('UP', 'Укр почта')], max_length=2)),
                ('phone', models.CharField(max_length=200)),
                ('telegram', models.CharField(blank=True, max_length=200)),
                ('additional', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Koots.buyers')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Koots.sheets')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
